export default {
    "5411":  "Grocery Stores, Supermarkets",
    "5812":  "Eating Places, Restaurants",
    "5541":  "Service Stations (with or without Ancillary Services)",
    "7832":  "Motion Picture Theaters",
    "4121":  "Taxicabs, Limousines",
    "7230":  "Barber and Beauty Shops",
    "5814":  "Fast Food Restaurants",
    "5912":  "Drug Stores, Pharmacies",
    "5941":  "Sporting Goods Stores",
    "5816":  "Digital Goods: Games",
    "5691":  "Men's, Women's, and Children's Clothing Stores",
    "5651":  "Family Clothing Stores",
    "5999":  "Miscellaneous and Specialty Retail Stores",
    "5732":  "Electronics Stores",
    "7922":  "Theatrical Producers (Except Motion Pictures), Ticket Agencies",
    "5811":  "Caterers",
    "5813":  "Drinking Places (Alcoholic Beverages), Bars, Taverns, Cocktail Lounges",
    "7995":  "Betting, including Lottery Tickets, Casino Gaming Chips, Off-Track Betting, and Wagers",
    "5992":  "Florists",
    "8011":  "Doctors, Physicians, Surgeons (Not Mental Health) - Not elsewhere classified",
}